#version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CACHE_TYPE: redis
      WORDPRESS_CACHE_REDIS_HOST: redis
      WORDPRESS_CACHE_REDIS_PORT: 6379
      WORDPRESS_DEBUG: TRUE
    volumes:
      - ./wordpress:/var/www/html:rw
    networks:
      - blog-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`myblog.local`) || Host(`localhost`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/wp-content &&
        docker-entrypoint.sh apache2-foreground"

  db:
    image: mysql:5.7
    #image: mysql:latest #ei toiminnut suoraan, selvitettävä
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init/01_load_timezones.sql:/docker-entrypoint-initdb.d/01_load_timezones.sql
      - ./db_init/02_wordpress_init.sql:/docker-entrypoint-initdb.d/02_init.sql
    networks:
      - blog-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - blog-network

  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - blog-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - blog-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.myblog.local`) || Host(`phpmyadmin.localhost`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

volumes:
  db_data:

networks:
  blog-network:
